---
repos:
    # General

    - repo: meta
      hooks:
          - id: check-hooks-apply
          - id: check-useless-excludes
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: check-added-large-files
          - id: check-case-conflict
          - id: check-executables-have-shebangs
          - id: check-merge-conflict
          - id: check-toml
          - id: check-xml
          - id: check-yaml
    - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
      rev: 3.1.2
      hooks:
          - id: editorconfig-checker
    - repo: https://github.com/gitleaks/gitleaks
      rev: v8.23.1
      hooks:
          - id: gitleaks
    - repo: https://github.com/jorisroovers/gitlint
      rev: v0.19.1
      hooks:
          - id: gitlint

    # Language-specific

    - repo: https://github.com/doublify/pre-commit-rust
      rev: v1.0
      hooks:
          - id: clippy
          - id: cargo-check
          - id: fmt
    - repo: https://github.com/scop/pre-commit-shfmt
      rev: v3.13.1-1
      hooks:
          - id: shfmt
    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: v0.43.0
      hooks:
          - id: markdownlint
            exclude: |
                  (?x)^(
                      CHANGELOG.md
                  )$
    - repo: https://github.com/hukkin/mdformat
      rev: 1.0.0
      hooks:
          - id: mdformat
            exclude: |
                  (?x)^(
                      CHANGELOG.md
                  )$
