[package]
name = "memy"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.5", features = ["derive"] }
dirs = "5.0"
predicates = "3.1.3"
rusqlite = "0.30"

[dev-dependencies]
assert_cmd = "2"
tempfile = "3"
