[package]
name = "memy"
version = "0.1.0"
edition = "2021"
authors = ["Andrew Ferrier <andrew.ferrier@example.com>"]
description = "Track and recall frequently and recently used files or directories."
license = "MIT"
repository = "https://github.com/andrewferrier/memy"
readme = "README.md"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.5", features = ["derive"] }
config = { version = "0.15.13", features = ["toml"] }
dirs-next = "2.0.0"
env_logger = "0.11"
glob = "0.3.2"
log = "0.4.27"
rusqlite = "0.30"
serde = "1.0.219"
toml = "0.9.2"

[dev-dependencies]
assert_cmd = "2"
tempfile = "3"
