[package]
name = "memy"
version = "0.4.0"
edition = "2021"
authors = ["Andrew Ferrier <andrew.ferrier@example.com>"]
description = "Track and recall frequently and recently used files or directories."
license = "MIT"
repository = "https://github.com/andrewferrier/memy"
readme = "README.md"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.5", features = ["derive"] }
clap_complete = "4.5.55"
config = { version = "0.15.13", features = ["toml"] }
env_logger = "0.11"
ignore = "0.4"
log = "0.4.27"
rusqlite = { version = "0.37", features = ["bundled"] }
serde = "1.0.219"
toml = "0.9.2"
xdg = "3.0.0"

[dev-dependencies]
assert_cmd = "2"
tempfile = "3"
