#!/usr/bin/env bash

_memy_note_hook() {
  # For performance
  [[ -n "$BASH_COMMAND" ]] || return

  local -a words
  IFS=' ' read -r -a words <<<"$BASH_COMMAND"

  for word in "${words[@]}"; do
    # shellcheck disable=SC2154
    if [[ -e "$word" ]]; then
      memy \
        --config denied_files_warn_on_note=false \
        --config missing_files_warn_on_note=false \
        note "$word"
    fi
  done
}

_memy_install_debug_trap() {
  if [[ -n "${_MEMY_BASH_HOOK_INSTALLED:-}" ]]; then
    return 0
  fi

  # FIXME: This is not very reliable as it will still overwrite existing DEBUG traps -
  # should improve this with something like
  # https://github.com/rcaloras/bash-preexec
  trap "_memy_note_hook" DEBUG

  _MEMY_BASH_HOOK_INSTALLED=1
}

_memy_install_debug_trap

_memy_cd() {
  local selected
  selected=$(memy list -d -s)
  # shellcheck disable=SC2164
  [[ -n "$selected" ]] && cd "${selected/#\~/$HOME}"
}

alias memy-cd='_memy_cd'

if ! declare -f z &>/dev/null && ! command -v z &>/dev/null; then
  function z() {
    if [[ $# -eq 1 && $1 == '-' ]]; then
      # shellcheck disable=SC2164
      cd "${OLDPWD}"
      return
    fi
    local result
    result="$(memy z -- "$@")" && cd "${result/#\~/$HOME}"
  }
fi

if ! declare -f zi &>/dev/null && ! command -v zi &>/dev/null; then
  alias zi='_memy_cd'
fi
