#!/usr/bin/env bash

_memy_note_hook() {
  # For performance
  [[ -n "$BASH_COMMAND" ]] || return

  local -a words
  IFS=' ' read -r -a words <<<"$BASH_COMMAND"

  for word in "${words[@]}"; do
    local expanded="${word/#\~/$HOME}"
    # shellcheck disable=SC2154
    if [[ -e "$expanded" ]]; then
      memy \
        --config denied_files_warn_on_note=false \
        --config missing_files_warn_on_note=false \
        note "$expanded"
    fi
  done
}

_memy_install_debug_trap() {
  if [[ -n "${_MEMY_BASH_HOOK_INSTALLED:-}" ]]; then
    return 0
  fi

  # FIXME: This is not very reliable as it will still overwrite existing DEBUG traps -
  # should improve this with something like
  # https://github.com/rcaloras/bash-preexec
  trap "_memy_note_hook" DEBUG

  _MEMY_BASH_HOOK_INSTALLED=1
}

_memy_install_debug_trap

_memy_select() {
  local selected
  selected=$(memy --color always list "$@" -s) || return
  [[ -n "$selected" ]] || return 1
  echo "${selected/#\~/$HOME}"
}

_memy_cd() {
  local selected
  selected=$(_memy_select -d) || return
  # shellcheck disable=SC2164
  cd "$selected"
}

alias memy-cd='_memy_cd'

_memy_open() {
  local selected
  selected=$(_memy_select -f) || return
  memy open "$selected"
}

alias memy-open='_memy_open'

_memy_go() {
  local selected
  selected=$(_memy_select) || return
  if [[ -d "$selected" ]]; then
    # shellcheck disable=SC2164
    cd "$selected"
  else
    memy open "$selected"
  fi
}

alias memy-go='_memy_go'

if ! declare -f z &>/dev/null && ! command -v z &>/dev/null; then
  function z() {
    if [[ $# -eq 1 && $1 == '-' ]]; then
      # shellcheck disable=SC2164
      cd "${OLDPWD}"
      return
    fi
    local result
    result="$(memy z -- "$@")" && cd "${result/#\~/$HOME}"
  }
fi

if ! declare -f zi &>/dev/null && ! command -v zi &>/dev/null; then
  function zi() {
    local result
    result="$(memy z -i -- "$@")" && cd "$result"
  }
fi
